### ISSUE TITLE
feat: please add zee channels 

### ISSUE THREAD

**Issue by Manguman69** [JioTV-Go/jiotv_go#490] opened 2024-12-31 04:52 UTC
### Feature description

there are only zee news channels no entertainment and no movie channels of zee

please add it

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itsyourap** [comment] 2024-12-31 06:42
Duplicate of #464

**Closed by itsyourap** 2024-12-31 06:42 UTC
Labels: enhancement
