### ISSUE TITLE
feat: Add Extra channels 

### ISSUE THREAD

**Issue by Maddy980** [JioTV-Go/jiotv_go#461] opened 2024-10-15 15:36 UTC
### Feature description

In new update there is no option to add extra channels through custom binary, please add as per your convenience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment] 2024-10-17 09:30
Duplicate of #449

**Closed by rabilrbl** 2024-10-17 09:30 UTC
Labels: enhancement
