### ISSUE TITLE
feat: Add Zee Channels like Zee TV, Zee Cinema, AND TV, AND Pictures ... etc

### ISSUE THREAD

**Issue by mohit-prakash** [JioTV-Go/jiotv_go#464] opened 2024-10-21 19:54 UTC
### Feature description

Add Zee Channels like Zee TV, Zee Cinema, AND TV, AND Pictures ... etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itsyourap** [comment] 2024-10-23 02:07
Duplicate of #425

**Comment by SparkleNaru** [comment] 2024-11-02 07:06
In addition could u plz add Zee Network Channels into this (Telugu)

**Comment by itsyourap** [comment] 2024-11-02 07:11
> In addition could u plz add Zee Network Channels into this (Telugu)

jiotv_go contains the channels already present in JioTV. Nothing more or less than that.

**Closed** 2024-11-07 02:27 UTC
Labels: enhancement
